version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_SDK_API_KEY=${GOOGLE_SDK_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - IMAGES_DIR=${IMAGES_DIR}
    volumes:
      - ./data/aquarium_images:${IMAGES_DIR}
      - ./data/db:/app/db  # For SQLite database persistence
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend-pc:
    build: 
      context: ./frontend-pc
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "${FRONTEND_PC_PORT}:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend

  frontend-vr:
    build: ./frontend-vr
    ports:
      - "${FRONTEND_VR_PORT}:3001"
    depends_on:
      - backend