services:
  backend:
    build: ./backend
    network_mode: "host"
    environment:
      # AI provider keys
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # AI analysis settings
      - AI_API_TIMEOUT=${AI_API_TIMEOUT}
      - AI_API_MAX_RETRIES=${AI_API_MAX_RETRIES}
      - AI_MAX_TOKENS=${AI_MAX_TOKENS}
      # tank information
      - TANK_TEMP_MIN=${TANK_TEMP_MIN}
      - TANK_TEMP_MAX=${TANK_TEMP_MAX}
      # compute node settings
      - LOCATION=${LOCATION}
      - TIMEZONE=${TIMEZONE}
      - DATA_DIR=${DATA_DIR}
      - IMAGES_DIR=${IMAGES_DIR}
      - DATABASE_DIR=${DATABASE_DIR}
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      # security settings
      - CORS_ORIGINS=${CORS_ORIGINS}
      - CORS_MAX_AGE=${CORS_MAX_AGE}
      # camera devices
      - CAMERA_DEVICES=${CAMERA_DEVICES}
      - CAMERA_FPS=${CAMERA_FPS}
      - CAMERA_IMG_TYPE=${CAMERA_IMG_TYPE}
      - CAMERA_MAX_DIM=${CAMERA_MAX_DIM}
      - CAMERA_CAM_WIDTH=${CAMERA_CAM_WIDTH}
      - CAMERA_CAM_HEIGHT=${CAMERA_CAM_HEIGHT}
      - CAMERA_MAX_IMAGES=${CAMERA_MAX_IMAGES}
      - CAMERA_MIN_FREE_SPACE_MB=${CAMERA_MIN_FREE_SPACE_MB}
      - CAMERA_STREAM_TOGGLE_DELAY=${CAMERA_STREAM_TOGGLE_DELAY}
      # scan settings
      - SCAN_CAMERA_ID=${SCAN_CAMERA_ID}
      - SCAN_ENABLED=${SCAN_ENABLED}
      - SCAN_INTERVAL=${SCAN_INTERVAL}
      - SCAN_SLEEP_TIME=${SCAN_SLEEP_TIME}
      - SCAN_TRAJECTORIES=${SCAN_TRAJECTORIES}
      # Robot server settings
      - ROBOT_SERVER_HOST=${ROBOT_SERVER_HOST}
      - ROBOT_SERVER_PORT=${ROBOT_SERVER_PORT}
      - ROBOT_SERVER_BUFFER_SIZE=${ROBOT_SERVER_BUFFER_SIZE}
      - ROBOT_SERVER_INITIAL_RETRY_DELAY=${ROBOT_SERVER_INITIAL_RETRY_DELAY}
      - ROBOT_SERVER_MAX_RETRY_DELAY=${ROBOT_SERVER_MAX_RETRY_DELAY}
      - ROBOT_SERVER_RETRY_BACKOFF=${ROBOT_SERVER_RETRY_BACKOFF}
      - ROBOT_SERVER_COMMAND_TIMEOUT=${ROBOT_SERVER_COMMAND_TIMEOUT}
      - ROBOT_SERVER_MAX_CONNECT_ATTEMPTS=${ROBOT_SERVER_MAX_CONNECT_ATTEMPTS}
      - ROBOT_SERVER_KEEP_ALIVE_INTERVAL=${ROBOT_SERVER_KEEP_ALIVE_INTERVAL}
      - ROBOT_RAW_CMD_MAX_RETRY=${ROBOT_RAW_CMD_MAX_RETRY}
    volumes:
      - ./data:/app/data:rw
      - /dev:/dev:rw
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/video2:/dev/video2"
      - "/dev/video3:/dev/video3"
      - "/dev/video4:/dev/video4"
      - "/dev/video5:/dev/video5"
    group_add:
      - video
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST_IP}:8000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    user: "${USER_ID}:${GROUP_ID}"

  frontend-pc:
    build: 
      context: ./frontend-pc
      args:
        - BACKEND_URL=http://${HOST_IP}:8000
        - CAMERA_IMG_TYPE=${CAMERA_IMG_TYPE:-jpg}
        - IMAGE_FETCH_INTERVAL=${IMAGE_FETCH_INTERVAL:-30000}
        - TRAJECTORY_FETCH_INTERVAL=${TRAJECTORY_FETCH_INTERVAL:-30000}
        - ANALYSIS_POLL_INTERVAL=${ANALYSIS_POLL_INTERVAL:-10000}
    network_mode: "host"
    environment:
      - BACKEND_URL=http://${HOST_IP}:8000
      - HOST=0.0.0.0
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST_IP}:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend-vr:
    build: ./frontend-vr
    network_mode: "host"
    environment:
      - BACKEND_URL=http://${HOST_IP}:8000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST_IP}:3001"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data:
    driver: local

networks:
  default:
    name: aquarius-network
  host:
    external: true