version: '3.8'

services:
  backend:
    build: ./backend
    networks:
      - aquarius-net
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - DATA_DIR=${DATA_DIR}
      - IMAGES_DIR=${IMAGES_DIR}
      - DATABASE_DIR=${DATABASE_DIR}
      - DATABASE_URL=${DATABASE_URL}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_SDK_API_KEY=${GOOGLE_SDK_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - CAMERA_FPS=${CAMERA_FPS}
      - CAMERA_FRAME_BUFFER=${CAMERA_FRAME_BUFFER}
      - CAMERA_CAM_WIDTH=${CAMERA_CAM_WIDTH}
      - CAMERA_CAM_HEIGHT=${CAMERA_CAM_HEIGHT}
      - CAMERA_MAX_IMAGES=${CAMERA_MAX_IMAGES}
      - CAMERA_MIN_FREE_SPACE_MB=${CAMERA_MIN_FREE_SPACE_MB}
      - TANK_TEMP_MIN=${TANK_TEMP_MIN}
      - TANK_TEMP_MAX=${TANK_TEMP_MAX}
      - TANK_PH_MIN=${TANK_PH_MIN}
      - TANK_PH_MAX=${TANK_PH_MAX}
      - TANK_AMMONIA_MAX=${TANK_AMMONIA_MAX}
      - TANK_NITRITE_MAX=${TANK_NITRITE_MAX}
      - TANK_NITRATE_MAX=${TANK_NITRATE_MAX}
    volumes:
      - ./data:/data
      - ${CAMERA_DEVICE}:/dev/video0
    devices:
      - "${CAMERA_DEVICE}:/dev/video0"
    group_add:
      - video
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    user: "${UID}:${GID}"

  # Rest of the services remain the same...
  frontend-pc:
    build: 
      context: ./frontend-pc
      args:
        - REACT_APP_API_URL=http://localhost:${BACKEND_PORT}
    networks:
      - aquarius-net
    ports:
      - "${FRONTEND_PC_PORT:-3000}:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:${BACKEND_PORT}
      - REACT_APP_POLL_INTERVAL=${REACT_APP_POLL_INTERVAL}
      - REACT_APP_IMAGE_MAX_WIDTH=${REACT_APP_IMAGE_MAX_WIDTH}
      - REACT_APP_IMAGE_MAX_HEIGHT=${REACT_APP_IMAGE_MAX_HEIGHT}
      - REACT_APP_TEMP_WARNING_MIN=${REACT_APP_TEMP_WARNING_MIN}
      - REACT_APP_TEMP_WARNING_MAX=${REACT_APP_TEMP_WARNING_MAX}
      - REACT_APP_PH_WARNING_MIN=${REACT_APP_PH_WARNING_MIN}
      - REACT_APP_PH_WARNING_MAX=${REACT_APP_PH_WARNING_MAX}
      - REACT_APP_STAT_DECIMAL_PLACES=${REACT_APP_STAT_DECIMAL_PLACES}
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend-vr:
    build: ./frontend-vr
    networks:
      - aquarius-net
    ports:
      - "${FRONTEND_VR_PORT:-3001}:3001"
    environment:
      - VITE_API_URL=http://localhost:${BACKEND_PORT:-8000}
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data:
    driver: local

networks:
  aquarius-net:
    driver: bridge