services:
  backend:
    build: ./backend
    networks:
      - aquarius-net
    ports:
      - "8000:8000"
    environment:
      - DATA_DIR=${DATA_DIR}
      - IMAGES_DIR=${IMAGES_DIR}
      - DATABASE_DIR=${DATABASE_DIR}
      - DATABASE_URL=${DATABASE_URL}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - VLM_API_TIMEOUT=${VLM_API_TIMEOUT}
      - VLM_API_MAX_RETRIES=${VLM_API_MAX_RETRIES}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - CORS_MAX_AGE=${CORS_MAX_AGE}
      - CAMERA_FPS=${CAMERA_FPS}
      - CAMERA_FRAME_BUFFER=${CAMERA_FRAME_BUFFER}
      - CAMERA_IMG_TYPE=${CAMERA_IMG_TYPE}
      - CAMERA_MAX_DIM=${CAMERA_MAX_DIM}
      - CAMERA_CAM_WIDTH=${CAMERA_CAM_WIDTH}
      - CAMERA_CAM_HEIGHT=${CAMERA_CAM_HEIGHT}
      - CAMERA_MAX_IMAGES=${CAMERA_MAX_IMAGES}
      - CAMERA_MIN_FREE_SPACE_MB=${CAMERA_MIN_FREE_SPACE_MB}
      - TANK_TEMP_MIN=${TANK_TEMP_MIN}
      - TANK_TEMP_MAX=${TANK_TEMP_MAX}
      - TANK_PH_MIN=${TANK_PH_MIN}
      - TANK_PH_MAX=${TANK_PH_MAX}
      - TANK_AMMONIA_MAX=${TANK_AMMONIA_MAX}
      - TANK_NITRITE_MAX=${TANK_NITRITE_MAX}
      - TANK_NITRATE_MAX=${TANK_NITRATE_MAX}
    volumes:
      - ./data:/app/data:rw
      - /dev:/dev:rw  # Map all devices
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/video2:/dev/video2"
      - "/dev/video3:/dev/video3"
      - "/dev/video4:/dev/video4"
    group_add:
      - video
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    user: "${UID}:${GID}"

  frontend-pc:
    build: 
      context: ./frontend-pc
      args:
        - BACKEND_URL=http://${HOST_IP}:8000
    networks:
      - aquarius-net
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://${HOST_IP}:8000
      - HOST=0.0.0.0
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend-vr:
    build: ./frontend-vr
    networks:
      - aquarius-net
    ports:
      - "3001:3001"
    environment:
      - BACKEND_URL=http://${HOST_IP}:8000
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data:
    driver: local

networks:
  aquarius-net:
    driver: bridge