version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data/aquarium_images:/tmp/aquarium_images  # Ensure images persist outside the container
  frontend-pc:
    build: ./frontend-pc
    ports:
      - "3000:3000"
  frontend-vr:
    build: ./frontend-vr
    ports:
      - "3001:3001"