version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    env_file:
      - ./.env

  frontend-dashboard:
    build: ./frontend-dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-dashboard:/app
    env_file:
      - ./.env

  frontend-vr:
    build: ./frontend-vr
    ports:
      - "4000:3000"
    volumes:
      - ./frontend-vr:/app
    env_file:
      - ./.env
